---
- hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
      - name: passlib
      - name: jsondiff
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
  roles:
    - role: geerlingguy.pip
      tags:
        - pip
    - role: geerlingguy.docker
      tags:
        - docker
    - role: swarm
      tags:
        - swarm
    - role: traefik
      tags:
        - traefik
    - role: swarmpit
      tags:
        - swarmpit
    - role: swarmprom
      tags:
        - swarmprom
    - role: portainer
      tags:
        - portainer