traefik_email: certs@example.com
traefik_domain: traefik.local.example.com
traefik_passwd_file: /var/traefik/passwd
traefik_username: admin
traefik_password: changethis

#le_dns_auth:
#  provider: azure
#  credentials:
#    - { name: azure_client_id, value: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", as_file: true}
#    - { name: azure_client_secret, value: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", as_file: true}
#    - { name: azure_subscription_id, value: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", as_file: true}
#    - { name: azure_tenant_id, value: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", as_file: true}
#    - { name: azure_resource_group, value: "XXXXXXXX", as_file: true}

le_dns_auth:
  provider: route53
  resolvers: ns-1505.awsdns-60.org
  credentials:
    - { name: aws_profile, value: "default", as_file: false}
    - { name: aws_region, value: "us-west-1", as_file: false}
    - { name: aws_hosted_zone_id, value: "ZXXXXXXXXXXXX", as_file: false}
