---
- name: Get node info
  community.docker.docker_node_info:
    self: true
  register: node_info
  tags:
  - always

- name: Merge labels
  community.docker.docker_node:
    hostname: "{{ node_info.nodes[0].ID }}"
    labels:
      swarmpit.db-data: "true"
      swarmpit.influx-data: "true"
    labels_state: merge
  tags:
  - docker-labels
  - config

- name: Create the Swarm appdir
  file:
    path: /swarm/swarmpit
    state: directory
    mode: '0755'
  tags:
  - setup
  - config

- name: Install docker-compose.yml
  template:
    src: swarmpit.yml.j2
    dest: /swarm/swarmpit/docker-compose.yml
  tags:
  - compose
  - config

- name: Deploy Swarmpit stack
  community.docker.docker_stack:
    state: present
    name: swarmpit
    compose:
      - /swarm/swarmpit/docker-compose.yml
  tags:
  - compose
  - deploy