---
- name: Add azure dns secrets
  community.docker.docker_secret:
    name: "{{ item.name }}"
    data: "{{ item.value }}"
    state: present
  loop: "{{ le_dns_auth.credentials }}"
  tags:
  - secrets
  - config
#- name: Add azure dns client id secret
#  community.docker.docker_secret:
#    name: azure_dns_client_id
#    data: "{{ azure_dns_client_id }}"
#    state: present
#  tags:
#  - secrets
#  - config
#
#- name: Add azure dns client secret secret
#  community.docker.docker_secret:
#    name: azure_dns_client_secret
#    data: "{{ azure_dns_client_secret }}"
#    state: present
#  tags:
#  - secrets
#  - config
#
#- name: Add azure dns subscription id secret
#  community.docker.docker_secret:
#    name: azure_dns_subscription_id
#    data: "{{ azure_dns_subscription_id }}"
#    state: present
#  tags:
#  - secrets
#  - config
#
#- name: Add azure dns tenant secret
#  community.docker.docker_secret:
#    name: azure_dns_tenant_id
#    data: "{{ azure_dns_tenant_id }}"
#    state: present
#  tags:
#  - secrets
#  - config
#
#- name: Add azure dns rg secret
#  community.docker.docker_secret:
#    name: azure_dns_resource_group
#    data: "{{ azure_dns_resource_group }}"
#    state: present
#  tags:
#  - secrets
#  - config